### ISSUE TITLE
V5 not working as expected.

### ISSUE THREAD

**Issue by fabltd** [harrisiirak/cron-parser#383]
Hello

The following sample code will work with V 4.9.0:

```
const cronParser = require('cron-parser');

console.log('cronParser keys:', Object.keys(cronParser)); // should show parseExpression

const interval = cronParser.parseExpression('*/5 * * * *');
console.log('Next time:', interval.next().toString());
```

npm install cron-parser@5.0.0

Now 

```
const interval = cronParser.parseExpression('*/5 * * * *');
                            ^

TypeError: cronParser.parseExpression is not a function
```

Is this meant to be broken what is the alternative?
